[package]
name = "bip32vanity"
version = "0.1.0"
authors = ["QDT <plutofever@users.noreply.github.com>"]

[dependencies]
secp256k1 = "0.6.3"
rust-crypto = "*"
rand = "*"
bitcoin = "*"
time = "*"
clap = "2.19.0"
indicatif = "0.9.0"

